### ISSUE TITLE
Dependency problem

### ISSUE THREAD

**Issue by EasonFeng5870** [iresty/lua-resty-etcd#16]
Could you guys tell where `local tab_nkeys = require "table.nkeys"` is from ?

thanks

**Comment by membphis** [comment]
https://github.com/openresty/luajit2#tablenkeys

please use the latest openresty `1.15.8.1`, it it released with openresty.

**Comment by EasonFeng5870** [comment]
we can't use that version , so I just modified it.

thanks.
