### ISSUE TITLE
Couldn't install lua-resty-etcd v0.8 via luarocks

### ISSUE THREAD

**Issue by orchaton** [iresty/lua-resty-etcd#48]
When I try to install lua-resty-etcd using luarocks I get following error:
```
luarocks --local install lua-resty-etcd 0.8
Installing http://luarocks.org/repositories/rocks/lua-resty-etcd-0.8-0.rockspec
Cloning into 'lua-resty-etcd'...
warning: Could not find remote branch v0.8 to clone.
fatal: Remote branch v0.8 not found in upstream origin

Error: Failed cloning git repository.
```

It seems that rockspec refers to non existing tag v0.8:
https://github.com/iresty/lua-resty-etcd/blob/0.8/rockspec/lua-resty-etcd-0.8-0.rockspec#L5

**Comment by moonming** [comment]
what's your version of `luarocks`?
`luarocks --local install lua-resty-etcd 0.8` works well in my side.

**Comment by orchaton** [comment]
```
$ luarocks --version
/usr/bin/luarocks 2.4.0
LuaRocks main command-line interface
```

After someone pushed a v0.8 I've managed to install it! Thanks :)
