### ISSUE TITLE
feature: supported v3 API of etcd.

### ISSUE THREAD

**Issue by membphis** [iresty/lua-resty-etcd#5]
we can add a API design first

**Comment by wujunze** [comment]
# etcd v3 api 设计
##  参考 golang 的 v3 Client 设计

1.  new 
get etcd client 

2.  put
Put puts a key-value pair into etcd.

3. get
Get retrieves keys.

4. delete
Delete deletes a key

5. compact
Compact compacts etcd KV history before the given rev.

6. do
Do applies a single Op on KV without a transaction

7. txn
Txn creates a transaction.

**Comment by membphis** [comment]
the action `new`, `put`, `get` and `delete` are easy to understand.

`compact`, `do` and `txn`, we need a simple use case to make it clearer.
