### ISSUE TITLE
error when connect the etcd

### ISSUE THREAD

**Issue by wuchencm** [iresty/lua-resty-etcd#52]
2020/02/21 04:59:32 [error] 16028#16028: *181 [lua] v2.lua:337: get(): failed to json decode: Expected value but found invalid token at character 1, client: 192.168.0.105, server: localhost, request: "GET /gray HTTP/1.1", host: "192.168.0.107"

1 the set methd is ok

`
local cli, err = require("resty.etcd").new({prototol = "v2", http_host = "http://127.0.0.1:2379"})
local res, err = cli:get('/test/gray/123-456-789')

ngx.print('hello')
`

**Comment by membphis** [comment]
I guess the value is not a JSON value, you can print more log for detail.

**Comment by wuchencm** [comment]
> detail

![{E2F9049A-DA1D-4CA2-A4A4-E3B2B0B7E7A1}_20200221215329](https://user-images.githubusercontent.com/14210543/75039951-b560e100-54f4-11ea-9dfe-6f86123fe9e8.jpg)

**Comment by membphis** [comment]
https://github.com/iresty/lua-resty-etcd/blob/master/api_v2.md#set

`syntax: res, err = cli:set(key:string, val:JSON value [, ttl:int])`

`lua-resty-etcd` only support JSON value .
